### ISSUE TITLE
Ryan Individual Final Review Ticket

### ISSUE THREAD

**Issue by ryanmgds** [jli615/lebroncs#48]

**Comment by RohanKoshy** [comment]
TOTAL SCORE: 5/6

Topic 1
Relation to CB topic: 1/1
Command of Technical Topic: 0.5/1
Vibe: 1/1
Total Score: 2.5/3

Topic 2
Relation to CB topic: 1/1
Command of Technical Topic: 0.5/1
Vibe: 1/1
Total Score: 3/3

Comments:

Good use of JavaScript to create tables, less redundant than html
Good explanation of the JavaScript building the table for frontend
Good explanation of the logic of how a for loop works and the syntax of a for loop.

Improvement

Could have better understanding of modeling, such as encapsulation.

**Comment by ghost** [comment]
**TOTAL SCORE: 5/6**

Topic 1
Relation to CB topic: 1/1
Command of Technical Topic: 0.75/1
Vibe: 0.75/1
Total Score: 2.5/3

Topic 2
Relation to CB topic: 1/1
Command of Technical Topic: 0.5/1
Vibe: 1/1
Total Score: 2.5/3

Comments:
- Creative use of array to fill in stats tables 
- Seems like the stats tables serve a strong purpose for the theme of the website 
- The java script for the stats tables is a good for now, should probably look into using a database/api feature from here 

Improvement:
- It is good that you label it as encapsulation, but your second topic may require a better explanation of technicals

**Comment by jli615** [comment]
TOTAL SCORE: 5/6

Topic 1
Relation to CB topic: 1/1
Command of Technical Topic: 0.5/1
Vibe: 1/1
Total Score: 2.5/3

Topic 2
Relation to CB topic: 1/1
Command of Technical Topic: 0.5/1
Vibe: 1/1
Total Score: 2.5/3

Comments:
- Good job effectively using an array to do stats table
- Solid work utilizing JavaScript to make the frontend look good
- Good explanation of for loop and encapsulation

Improvement
- Might be more efficient if you use an API instead of manually inputing stats

**Comment by jm1021** [comment]
1. Shared some JavaScript and processing list (soft coded).   In a demonstration like this we should be talking about future, particularly since we have had databases for a couple of weeks.  You should be adding and doing real stats by end of the trimester, not soft coded stats hardwired in HTML files.
2. Second example is talking about loops and classes.   This is not a PBL example.
4.75/6

Comments for you and Team.  R. Koshy was person in team that was showing command and analysis with Diagram and was looking well prepared.  This should have stood out in scoring and reviews.  Did not see it.  1.5/2
